### PR TITLE
chore: prepare the release of version 0.26.0

### PR DESCRIPTION
**Pull request by JKRhb**
This PR makes some preparations for the release of version 0.26.0 and updates the changelog.

### CODE REVIEW

**Comment by Apollon77** [comment]
I try to find time on the weeknd for all the PRs - I ned to finish one other topic before that but i'm close :-))

I had some fin with Amazon Alexa stuff some days because of changes by Amazon ... that killed my schedule a bit ...

**Comment by JKRhb** [comment]
Ping @Apollon77? :)

**Comment by Apollon77** [comment]
try to do next days ... was some days off because ofg family stuff, sorry

**Comment by Apollon77** [comment]
I never saw that automatic generation till now :-)) But yes we could also use this and remove the changelog file ...

**Comment by JKRhb** [comment]
> I never saw that automatic generation till now :-)) But yes we could also use this and remove the changelog file ...

Seems to be a new future :) I think it went live a couple of weeks ago but its formal introduction was on the recent Github Universe event, if I am not mistaken. Should save some time in the future in any case :) 

Alternatively we could also keep the changelog file and copy the generated release notes over?

**Comment by Apollon77** [comment]
lets leave in0.26.0 and remove for 1.0

**Pull request merged**
