### PR TITLE
Fix index out of range

### PR DESCRIPTION
**Pull request by neich**
Add guard to check if token length is > 0 before removing request reference

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test?
Il giorno dom 19 lug 2015 alle 20:13 neich <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment]
also, would you like to be help maintaining this project? Check if you are ok with CONTRIBUTING.md, and then send a PR to add your details to the README.

**Comment by neich** [comment]
After further research, I've realized that this fix is not good. The problem is the Cooja MOTE is returning a response with a token length = 0, so the right behavior would be to raise an error. You can dismiss this PR, I'll send another with a proper fix.

**Comment by mcollina** [comment]
Great! I'm waiting :)

**Pull request closed without merging**
