### PR TITLE
fix: use correct file extension for `models` file

### PR DESCRIPTION
**Pull request by JKRhb**
This PR fixes another typescript related bug: As the `models` file so far used the `.d.ts` file extension, its contents were ignored during transcompilation, therefore preventing the use of the library in other typescript projects. Renaming the file to `models.d.ts` serves as an easy fix to this problem.

While I was at it I added more types from `models.ts` to the export list in `index.ts` as missing types also seem to have caused some issues beforehand.

Finally, I incremented the version number to `1.0.2` so that we could release a patched version immediately.

### CODE REVIEW

**Comment by JKRhb** [comment]
@Apollon77 Could you maybe have a quick look on this PR? :)

**Comment by Apollon77** [comment]
You do changelog&tag and I publish... again?

**Comment by JKRhb** [comment]
> You do changelog&tag and I publish... again?

Sounds great :) Changelog and release are created now :)

**Comment by Apollon77** [comment]
npm on it's way too.

If you need to "Ping" me directly I could also offer email, telegram, whatsapp or discord as additional communication ways beside Github issues 
:-)

**Comment by JKRhb** [comment]
> npm on it's way too.

Awesome, thank you :)

> 
> If you need to "Ping" me directly I could also offer email, telegram, whatsapp or discord as additional communication ways beside Github issues :-)

That's great! :) Do want to send me an email with your contact information (you can find my address on my profile)? I think using Discord or Telegram would work best for me :)

**Pull request merged**
