### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by Apollon77** [comment]
Hm ... should we kick nodejs 10? at least for testing?

**Comment by JKRhb** [comment]
> Hm ... should we kick nodejs 10? at least for testing?

Oh, yeah, after some quick research I think upgrading the node version for the linter workflow could fix the CI pipeline :)

**Comment by Apollon77** [comment]
aahh yes the linting was still done in nodejs 10. changed

**Comment by Apollon77** [comment]
wtf ... https://github.com/mcollina/node-coap/runs/4122430279?check_suite_focus=true#step:5:4

**Comment by JKRhb** [comment]
Hmm, maybe the error is caused by the caching step?

**Comment by Apollon77** [comment]
Caching step? Could be ... lets see

**Comment by JKRhb** [comment]
Hmm, my other theory would be that it is a node 16 problem. The installation fails under both Ubuntu and Windows using that node version, the others seem to be fine.

**Comment by Apollon77** [comment]
what we should do?

**Comment by Apollon77** [comment]
PS: (because just noticed it) ... should we publish the "test" dir in npm too?

**Comment by JKRhb** [comment]
> PS: (because just noticed it) ... do we need to publish the "test" dir in npm too? (in fact we did)

Oh, sorry, that is a very good point! I will change that for the typescript version. Or can we publish a 0.26.1 from a different branch?

**Comment by JKRhb** [comment]
> what we should do?

From what I've seen doing another quick search this problem might actually be related to the caching. Maybe we could try to comment that step out

**Comment by Apollon77** [comment]
https://github.com/actions/cache/blob/main/examples.md#using-multiple-systems-and-npm-config

**Comment by Apollon77** [comment]
But yes I will comment out

**Comment by JKRhb** [comment]
Okay, my cache theory is disproven :D

**Comment by Apollon77** [comment]
Ok, reson seems to be the eslint update and other packages ...

**Comment by JKRhb** [comment]
Maybe downgrading eslint to 7.x.x (for now) could solve the problem?

**Comment by Apollon77** [comment]
just did that :-)

**Comment by Apollon77** [comment]
This was it

**Comment by Apollon77** [comment]
happy review ;-)

**Review by JKRhb — APPROVED** [review]
LGTM ;)

**Pull request merged**
