### PR TITLE
chore: update tested node versions to 14, 16, and 18

### PR DESCRIPTION
**Pull request by JKRhb**

### CODE REVIEW

**Comment by JKRhb** [comment]
@Apollon77 Hmm, seems like Node 18 causes some problems. I think there was a multicast-related API change that causes that?

**Comment by Apollon77** [comment]
puuhh ... ist it that "network family parameter change"? Will be reverted in 18.2 as it seems

**Comment by JKRhb** [comment]
> puuhh ... ist it that "network family parameter change"? Will be reverted in 18.2 as it seems

Oh, you mean this one, right? https://github.com/nodejs/node/pull/41431#discussion_r841272416

**Comment by Apollon77** [comment]
yes

**Comment by JKRhb** [comment]
> nope ... not fixed by 18.2

I think the number of errors reduced from 10 to 4, though, so we're at least halfway there ;)

**Comment by JKRhb** [comment]
The latest version of Node 18 seems to have solved the issue :) So I would merge this PR.

**Pull request merged**
