### PR TITLE
Fix: Retrysend broken when passing socket to agent

### PR DESCRIPTION
**Pull request by blankm**
Fixes issue #202

### CODE REVIEW

**Comment by GiedriusM** [comment]
Thank you for finding the issue :) Could you check if adding `this._closing = false` to the `_doClose()` function solves the issue? To me it looks like it's the "deinitialization" problem, which leaves an invalid state, while the code in the init is supposed to run only once. IMO the fix should reflect that.

Also did you find a way to consistently reproduce the bug? It would be nice to have a test to catch this in the future :)

**Comment by blankm** [comment]
> Thank you for finding the issue :) Could you check if adding `this._closing = false` to the `_doClose()` function solves the issue? To me it looks like it's the "deinitialization" problem, which leaves an invalid state, while the code in the init is supposed to run only once. IMO the fix should reflect that.

The init is with the code provided meant to be run every time a new request is created, at least it is called each time a new request is created, so fixing the bug there (and there it actually is located) makes the most sense for me. The cleanup in this stack was written the way it is, so it's definitely not a bug of the deinitialization, since this behaves as intended by the author. The init does not behave as intended (when using externally provided sockets). One could discuss whether the way, this stack handles init and deinit could be done in another way, but that's not the point here. This "single-line-bugfix" solves the issue.

> 
> Also did you find a way to consistently reproduce the bug? It would be nice to have a test to catch this in the future :)
Yeah, provide an external socket , create a request to a server that exists, let it finish and then create a request to a sever that doesn't exist, the second request's promise will leave you wait forever. But I don't know whether this can be automated.

**Comment by blankm** [comment]
Are there plans to merge this PR? I am eagerly waiting for the npm package being updated with this bugfix, so that I can update my project to use the new version of the node-coap package.

**Comment by GiedriusM** [comment]
I would like to have a test case for this issue. So far all my attempts to reproduce it worked as expected.
For example:
```javascript
const coap = require('coap');
const dgram = require('dgram');

let coapTiming = {
  ackTimeout:0.25,
  ackRandomFactor: 1.0,
  maxRetransmit: 3,
  maxLatency: 2,
  piggybackReplyMs: 10
};
coap.updateTiming(coapTiming);

const server = coap.createServer();
server.on('request', (req, res) => {
  res.end();
});
server.listen(7892);

const sock = dgram.createSocket('udp4');
sock.bind();

const agent = new coap.Agent({ socket: sock });

const req = coap.request({ agent: agent, port: 7892 });
req.end();
req.on('response', (res) => {
  console.log('Req1 response');
  setImmediate(() => {
    const req2 = coap.request({ agent: agent, port: 7893 });
    req2.end();
  });
});
```
does emit timeout.

Looking into the agent, I can see that the `_closing` flag should not be set (to true) when an external socket is used:
```javascript
  if (!this._opts.socket)
    this._closing = true
```
How is `_closing` flag set in your case?

**Comment by blankm** [comment]
Without having a look at the code in detail, your idea seems to be valid, too.
I fixed it in
`Agent.prototype._init = function initSock(socket)`
since, the original code (I guess at the time, when no external sockets where used) set 
`this._closing` to false again there.
Your solution is valid if `this._closing` is only used for the purpose of closing the socket. But I have the code not in mind right now, so I can't say whether setting `this._closing` to like you suggest has any interference.

**Comment by GiedriusM** [comment]
> Yeah, provide an external socket , create a request to a server that exists, let it finish and then create a request to a sever that doesn't exist, the second request's promise will leave you wait forever. But I don't know whether this can be automated.

Could we focus on reproducing this in a test case? The problem is still confusing me.

**Comment by blankm** [comment]
Any updates here?
Testcase can be set up using a CoAP server that is killed after the first sucessful request, so a subsequent request should cause a timeout which it doesnt in the old code.

**Comment by GiedriusM** [comment]
> Testcase can be set up using a CoAP server that is killed after the first sucessful request, so a subsequent request should cause a timeout which it doesnt in the old code.

server.js:
```javascript
const coap = require('coap');

let counter = 0;

const server = coap.createServer();
server.on('request', (req, res) => {
  res.end('' + counter++);
});
server.listen(7892);
```

client.js:
```javascript
const coap = require('coap');
const dgram = require('dgram');

let coapTiming = {
  ackTimeout:0.25,
  ackRandomFactor: 1.0,
  maxRetransmit: 3,
  maxLatency: 2,
  piggybackReplyMs: 10
};
coap.updateTiming(coapTiming);

const sock = dgram.createSocket('udp4');
sock.bind();

const agent = new coap.Agent({ socket: sock });

function doRequest(res) {
  if (res) {
    console.log('Got response', res.payload.toString());
  }

  const req = coap.request({ agent: agent, port: 7892 });
  req.end();
  req.on('response', doRequest);
  req.on('timeout', () => { console.log('Timeout') });
  req.on('error', () => { sock.close() });
}


doRequest();
```

When I run only client.js I get a timeout.
When I run server.js, then client.js and then kill (ctlr+c) server.js I get a timeout.

This and all my previous attempts to reproduce the problem based on your description seems to have failed. Could you provide an example code that causes the issue or even better a complete test case for travis?

**Comment by kevinresol** [comment]
I realize the "bug" will occur when there is no explicit calling of `updateTiming()`. I think there should be some sensible defaults?

```js
// server.js
const coap = require('coap');

let counter = 0;

const server = coap.createServer();
server.on('request', (req, res) => {
	res.end('' + counter++);
});
server.listen(7892);
```

```js
// client.js
var coap = require('coap');

(function loop() {
	console.log('loop');
	var req = coap.request('coap://localhost:7892');
	req.on('response', () => setTimeout(loop, 1000));
	req.on('timeout', () => console.log('Timeout'));
	req.on('error', () => console.log('Error'));
	req.end();
})();
```

Steps: 
1. start server
2. start client
3. kill server

**Comment by JsonMa** [comment]
@Apollon77 Can you reproduce this problem? I can't reproduce it locally..

**Comment by Apollon77** [comment]
No I can‘t but the code change makes sense logically and when reading the issue and the Pr the fix seems to be proofed by users. Additionally it does not really break things so risk is ok. 

I learned that I can not repro anything and so I review things a bit different in these cases and more do a logical due dilligence. ;-)
Yes ideally each issue also adds a test that breaks without the test and then fixing it ... but sometimes this is just not possible.

**Comment by Apollon77** [comment]
@mcollina What do you thingk on how to handle such edgy cases like this?

**Comment by mcollina** [comment]
Unfortunately I do not have time to dig in.

**Comment by Apollon77** [comment]
I meaned more the general "approach" question ... ok to accept it if there was a proof by usersand code "makes sense" also if we can not really repoduce it? I would accept it ion such situations

**Comment by JsonMa** [comment]
@Apollon77 OK，I agree with it. And if someone approve this change would result in another bug, we revert it.

**Pull request merged**
