### PR TITLE
Added proxy tests referring:

### PR DESCRIPTION
**Pull request by ClaesNilsson**
https://github.com/mcollina/node-coap/issues/55
https://github.com/mcollina/node-coap/issues/56

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please format the tests so that they follows the structure of the of the others? So they will be picked by travis, too!

**Comment by dmoranj** [comment]
Maybe this PR is not needed anymore, or maybe it can be added in an examples folder. I've already created a small test that covers #55 and I'm in process of doing the same with #56.

**Comment by ClaesNilsson** [comment]
Thanks Daniel! 
So do you think that it adds any value if I add my tests to the examples folder?

**Comment by dmoranj** [comment]
It's a good question, I don't know what Matteo thinks about this: should we give as much examples as possible or should we give just small examples one per feature? I think the most interesting thing about the example was to show the bugs themselves, and that functionality is already exposed in the tests, but I prefer to listen to Matteo's opinion on the subject.

**Comment by mcollina** [comment]
I think it's ok to have some integration tests, added to ensure bugs like
this one. Let's put them in a folder like 'test/integration', so we know
what we are talking about.
Il giorno lun 25 mag 2015 alle 15:16 Daniel Moran <notifications@github.com>
ha scritto:

**Comment by ClaesNilsson** [comment]
Just to make sure that there is no misunderstanding. I create a subfolder under 'test' (or 'exampels'?) called 'integration' and under that folder with my tests called 'ProxyTests'?

**Comment by mcollina** [comment]
why not just putting them in 'test/integration'?
Il giorno mar 26 mag 2015 alle 11:23 Claes Nilsson <notifications@github.com>
ha scritto:

**Pull request closed without merging**
