### PR TITLE
fix: fix observe when receiving block2 response

### LINKED ISSUE #336: reset msg on separated response(observe) with block2 option
am facing an issue, 
1. node-coap is a client and sends a CON request with observe and block2 option.
2. serve response with ACK including block2 option with moreFlag set to false.
3. when the new data is ready at server its send a notification CON message with block2 and moreFlag=true here client sents RESET 
instead of ACK.
Am i doing something wrong here. 
export

### PR DESCRIPTION
**Pull request by JKRhb**
This PR incorporates the suggested change by @Thousif-khan and should fix #336.

### CODE REVIEW

**Comment by JKRhb** [comment]
I think we should probably merge #344 first (which addresses some more fundamental observe issues) and see afterwards if this PR is still needed.

**Comment by Apollon77** [comment]
Ok, I release a 1.0.8 with #34 in and then we test again

**Comment by JKRhb** [comment]
> Ok, I release a 1.0.8 with #34 in and then we test again

Awesome, thank you :)

**Comment by JKRhb** [comment]
Hmm. Not sure if the additional if check changed anything?

**Comment by Apollon77** [comment]
Will merge and release tonight. Sorry for the delay

**Pull request merged**
