### PR TITLE
Fix without timeout error when using existing socket

### PR DESCRIPTION
**Pull request by PeterEB**
I use an Agent with existing socket. It will call `agent._cleanUp()` to set `agent._closing` to be `true` as soon as it receive a response. Then `agent._doClose()` will be called and `req.sender._timer` will be cleared when I use the same Agent to send requests. Therefore, timeout error event will never be fired. I recognize that `agent._closing` should not be set to `true` when Agent using existing socket.

### CODE REVIEW

**Comment by neophob** [comment]
thanks for you PR @PeterEB. can you add a unit test for that case?

**Comment by PeterEB** [comment]
I've added a very simple test.

**Comment by GiedriusM** [comment]
Hi, @PeterEB! There has been some issues with Travis builds. Could you merge this branch with master branch, to see if the tests finally pass?

**Comment by PeterEB** [comment]
I've merged master branch. The tests are pass!

**Comment by neophob** [comment]
@GiedriusM should we merge?

**Pull request merged**
