### PR TITLE
Feat/188

### PR DESCRIPTION
**Pull request by everhardt**
An attempt to implement https://github.com/mcollina/node-coap/issues/188. Also added a test and made a comment about it in README.md

### CODE REVIEW

**Comment by ans-4175** [comment]
Nice attempt, helpful

**Comment by Apollon77** [comment]
@everhardt your PR needs a rebase against master. Thank you

**Comment by everhardt** [comment]
I’ve moved on to a different language for our CoAP handling and won’t be contributing here anymore, sorry.

**Comment by JKRhb** [comment]
Closing this PR, as there is #256 now as a follow-up.

**Pull request closed without merging**
