### PR TITLE
style: enforce indentation using two spaces

### PR DESCRIPTION
**Pull request by JKRhb**
This PR fixes the identation used in the repository and adds an eslint rule.

### CODE REVIEW

**Comment by JKRhb** [comment]
@Apollon77 Ehem, here is another one 😅 Should I just go forward with changes like these? I would transform the codebase gradually towards StandardJS compliance and then finally merge #251.

**Comment by Apollon77** [comment]
Puuhh ... Honestly this is the main part I do not like on TandardJS ... In my eyes 2 spaces is much less readable then 4 spaces ... and I use 4 spaces in all my other projects and we had such discussions several times and readability was always the main argument.
How you see it?
In this case the standard "do not support" me and so I don't care about standards in such cases ;-))

**Comment by Apollon77** [comment]
@mcollina @jkivilin maybe also opinions out there ?!

**Comment by Apollon77** [comment]
@JKRhb seems noone else have an opinion :-) can we stay with the 4 spaces? ;-)

**Comment by JKRhb** [comment]
> @JKRhb seems noone else have an opinion :-) can we stay with the 4 spaces? ;-)

Sure :) I will adjust the PR accordingly :) Regarding #251 I think it might be useful in general to create our own coding style as StandardJS is too far away from the current code base to keep the changes from being too drastic. I will maybe add a (not too extensive) list of possible ESlint rules to #251 where we can discuss if we want to add them.

I think the most useful change will be converting all those `var`s to `const` and `let` which will help with finding bugs. Apart of from this there are probably things that deserve a higher priority than coding style in the package – sorry again for being a bit obsessed with this topic ;)

**Comment by JKRhb** [comment]
Closed in favor of #255. CC @Apollon77

**Pull request closed without merging**
