### PR TITLE
bumb version and add Changelog file

### PR DESCRIPTION
**Pull request by Apollon77**
BEFORE we merge this we need to finally decide about https://github.com/mcollina/node-coap/pull/211 and pot. add it ... or ot :-)

### CODE REVIEW

**Comment by JsonMa** [comment]
> BEFORE we merge this we need to finally decide about #211 and pot. add it ... or ot :-)

lgtm...We may merge #211 first.

**Comment by Apollon77** [comment]
Just merge when you are ready and I Update here.

**Comment by Apollon77** [comment]
@mcollina @JsonMa Changelog finalized ... this would be the 0.24.0 I think ...

**Comment by JsonMa** [comment]
> @mcollina @JsonMa Changelog finalized ... this would be the 0.24.0 I think ...
Agree

**Comment by Apollon77** [comment]
Thank you @mcollina

**Pull request merged**
