### PR TITLE
Add missing checks for Buffer length before reading from it, fixes #216

### LINKED ISSUE #216: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds/
Exception:

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
at boundsError (internal/buffer.js:47:11)
at Buffer.readUInt32BE (internal/buffer.js:192:5)
at Agent.abort (/opt/iobroker/node_modules/coap/lib/agent.js:404:42)
at RetrySend. (/opt/iobroker/node_modules/coap/lib/agent.js:365:10)
at RetrySend.emit (events.js:198:13)
at Timeout. (/opt/iobroker/node_modules/coap/lib/retry_send.js:78:10)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)
```

The reason seems to be that in line https://github.com/mcollina/node-coap/blob/master/lib/agent.js#L407 it is assumed that req._packet.token is a valid buffer from valid length ... but this is not checked here ... and so it seems that in timeout cases or such this exception occurs.

I saw several other places in the code where the same pattern is used (reading that token without checking) ... in many other places it is checked that token exists, in other cases also that length is ===4 ... a bit inconsistent ;-)

If interested I could provide a PR, but I can not really test this case because I do not use such devices :-(

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by Apollon77** [comment]
@mcollina Any chance to get this merged?
This fix was checked and proofed by several users.

I will wait some more days before I publish a scoped package to fix it because it makes big problems for some users!

**Comment by mcollina** [comment]
would you like to step in and maintain this? I have no time/interested in this package anymore.

**Comment by Apollon77** [comment]
Thank you for the offer and honestly I also have many other libs and projects that costs most of my time ... And one of them uses this library - but I personally do not use coap devices (beside one Shelly device that never had that issue) :-(
So for now I only checked the code and saw missing checks and so I decided to provide a PR to address this "very high level" problem.

I would be happy with a release of that fix - if you do bot have time I would also be ok when you give me the rights (Apollon77 on GitHub, apollon77 on npm) ... but I do not know if I can promise to really maintain it better :-(

**Comment by Apollon77** [comment]
@mcollina I had a thought overnight ... let’s try it. How much i really can help will highly rely on the community and to get some other users support in reviewing the relevant PRs, but it can only get better ;-) (no offense ;-) )

**Comment by JsonMa** [comment]
> @mcollina I had a thought overnight ... let’s try it. How much i really can help will highly rely on the community and to get some other users support in reviewing the relevant PRs, but it can only get better ;-) (no offense ;-) )
I am also very interested in this project and would like to participate in the maintenance of this project if I have the opportunity.

**Comment by JsonMa** [comment]
@Apollon77  I totally agree with you, checking PRs and issues is the most important thing at present.

**Comment by Apollon77** [comment]
@mcollina If you need to discuss more details before giving me access just contact me on github@fischer-ka.de

**Comment by Apollon77** [comment]
This PR is ok for me  (can not add myself as reviewer)

**Pull request merged**
