### PR TITLE
standard updates

### PR DESCRIPTION
**Pull request by neophob**
Uff, I modified the code so the standard code style matches. Quite a couple if import could be removed. Most changes are quite non-invasive, but take a look at:
- middleware.js: function isObserve - wrong parameter
- helpers.js: function parseBlock2 - moreBlock2 flag
- agent.js: function _init - packet reference was unused

### CODE REVIEW

**Comment by neophob** [comment]
some tests are really flacky, for example

```
1) end-to-end formats should pass the 'Content-Format: application/link-format' option to the server if passed alongside the url:
     Error: done() called multiple times
```

any hints?

**Comment by mcollina** [comment]
Tests are passing on current master.
However, some of them are flaky, but they should pass, so it's probably some changes done by the reformatting.

**Comment by mcollina** [comment]
BTW, do you prefer standard or semistandard?

**Comment by neophob** [comment]
Yes, I'll take a look at them soon. Well about standard or semistandard - I worked with jshint in the past but standard is fine too - one of them is better than nothing an both help to detect bugs.

**Pull request closed without merging**
