### PR TITLE
feat: add support for FETCH, PATCH, and iPATCH

### PR DESCRIPTION
**Pull request by JKRhb**
This PR adds support for the FETCH, PATCH, and iPATCH CoAP methods, as specified in [RFC 8132](https://datatracker.ietf.org/doc/html/rfc8132). I still need to figure out what is actually needed to fully support these methods (besides the status codes), so this PR is for now only opened as a draft.

### CODE REVIEW

**Comment by JKRhb** [comment]
@Apollon77 It would be awesome if you could have a look on this PR :) For me it seems that there is actually no more logic necessary to support the new methods but maybe you could also have a look into RFC 8132?

**Comment by Apollon77** [comment]
I try to check next days ... seems "a lot" that you managed to do :-)

**Comment by JKRhb** [comment]
@Apollon77 I think this PR is now the only one that is left :) Would be awesome if you could have a look on it and proceed with merging if it is okay. I guess after that we can create a new release :)

**Comment by JKRhb** [comment]
@Apollon77 As this PR does not introduce the most complex new feature I would go ahead and merge it :) Let me know if you notice anything that should be changed then we could open a follow-up PR :)

**Comment by Apollon77** [comment]
LGTM

**Pull request merged**
